### ISSUE TITLE
Time for running example notebooks?

### ISSUE THREAD

**Issue by ncclementi** [bjmorgan/pyscses#10]
Hello there, 

How long are the Examples notebooks on the userguide are suppose to take? I'd like to have a reference so I can run them. I've been trying to run Example 1 and the times has gone over 10 min is that expected? 

Thanks

**Comment by bjmorgan** [comment]
@georgiewellock Can you add approximate timings to the userguides README, and note in the notebooks where there are any calculations that take a long time to run?

**Comment by georgiewellock** [comment]
I have added the approximate timings and machine specifications to both the README and the userguide notebooks: https://github.com/bjmorgan/pyscses/commit/8ceeab33d066e1a50ab6180a362cac95fac6f1db

Example notebooks 1 and 2 take significantly longer to run due to the Gouy-Chapman conditions. These require the Poisson-Boltzmann solver to be run repeatedly in order to minimise the difference between the mole fractions we pass in and the mole fractions which are calculated. Example 3 onwards (should) only take a few minutes.

**Comment by ncclementi** [comment]
Great, thanks for adding that I will be running the examples today!
